name: Publish App NuGet to GitHub Packages

on:
  push:
    branches: [ "Release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Create NuGet package
      run: dotnet pack --no-build -o .
    - name: Publish to GitHub Packages
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.KEYNUGET }} -s https://nuget.pkg.github.com/eamonnwatson/index.json --skip-duplicate
      
